#
# ftdi wrapper 
# ==================
#
# requrirements:
# -------------------
# * libftdi
# * swig
# * python2.6+
#
#
# building
# ----------------
# 1. scons
# 2. sudo scons install
#


import sys
import os
import commands

env = Environment()
env.ParseConfig('pkg-config --libs --cflags libftdi python-%d.%d'%(sys.version_info[0], sys.version_info[1]))

print(sys.version_info)

PYPLATPATH = filter(lambda x: "plat" in x, sys.path)[0]

swig_flags = commands.getoutput('pkg-config --cflags libftdi').rstrip().split(' ')
swig_flags.append('-I/usr/include')
swig_flags.append('-python')

lib = env.SharedLibrary( target='_ftdi.so', source='ftdi.i'.split(),
                    CPPPATH=['.', '$CPPPATH'],
                    SWIGFLAGS=swig_flags,
                    SHLIBPREFIX='',
                   )

env.Alias('install', env.Install(PYPLATPATH, [lib, 'ftdi.py']))

